/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.keagan.parkingmeterapp.view;

import com.keagan.parkingmeterapp.model.CalculateParkingAmountModel;
import com.keagan.parkingmeterapp.model.CalculatePayModel;
import com.keagan.parkingmeterapp.util.CalculateDenominations;
import com.keagan.parkingmeterapp.util.CreateTextFile;
import java.util.Date;
import com.keagan.parkingmeterapp.util.DateSelector;
import com.keagan.parkingmeterapp.util.FeeCalculator;
import com.keagan.parkingmeterapp.util.MakePaymentCalculator;
import com.keagan.parkingmeterapp.util.TimeCalculator;

/**
 *
 * @author User
 */
public class ParkingMeterMainForm extends javax.swing.JFrame {
    
    CalculateParkingAmountModel   calculateParkingAmountModel = new CalculateParkingAmountModel();
    CreateTextFile createTextFile = new CreateTextFile();
    CalculatePayModel calculatePayModel = new CalculatePayModel();
    /**
     * Creates new form ParkingMeterMainForm
     */
    public ParkingMeterMainForm() {
        initComponents();
        
        DateSelector date = new DateSelector();
        entryDateTF.setEditable(false);
        amountDueTextArea.setEditable(false);
        exitDateTF.setEditable(false);
        entryDateTF.setText(date.dateSelector());
        outputTextArea.setEditable(false);
        createTextFile.createFile();
        calculatePaymentBtn.setEnabled(false);
        payAmountBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        entryDateTF = new javax.swing.JTextField();
        nextDayEntryBtn = new javax.swing.JButton();
        prevDayEntryBtn = new javax.swing.JButton();
        exitDateTF = new javax.swing.JTextField();
        calculateExitDateBtn = new javax.swing.JButton();
        entryDateLabel = new javax.swing.JLabel();
        exitDateLabel = new javax.swing.JLabel();
        hoursIncrementBtn = new javax.swing.JButton();
        hoursDecrementBtn = new javax.swing.JButton();
        calculatePaymentBtn = new javax.swing.JButton();
        amountDueLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        amountDueTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        minutesIncrementBtn = new javax.swing.JButton();
        minutesDecrementBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tenCentSpinner = new javax.swing.JSpinner();
        twentyCentSpinner = new javax.swing.JSpinner();
        fiftyCentSpinner = new javax.swing.JSpinner();
        OneRandSpinner = new javax.swing.JSpinner();
        twoRandSpinner = new javax.swing.JSpinner();
        fiveRandSpinner = new javax.swing.JSpinner();
        tenRandSpinner = new javax.swing.JSpinner();
        twentyRandSpinner = new javax.swing.JSpinner();
        payAmountBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fiftyRandSpinner = new javax.swing.JSpinner();
        oneHundredRandSpinner = new javax.swing.JSpinner();
        twoHundredRandSpinner = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        adminBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parking Meter App");

        nextDayEntryBtn.setText("Next");
        nextDayEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextDayEntryBtnActionPerformed(evt);
            }
        });

        prevDayEntryBtn.setText("Prev");
        prevDayEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevDayEntryBtnActionPerformed(evt);
            }
        });

        calculateExitDateBtn.setText("Exit Date");
        calculateExitDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateExitDateBtnActionPerformed(evt);
            }
        });

        entryDateLabel.setText("Entry Date/Time");

        exitDateLabel.setText("Exit Date/Time");

        hoursIncrementBtn.setText("+");
        hoursIncrementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursIncrementBtnActionPerformed(evt);
            }
        });

        hoursDecrementBtn.setText("-");
        hoursDecrementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursDecrementBtnActionPerformed(evt);
            }
        });

        calculatePaymentBtn.setText("Calculate Payment");
        calculatePaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatePaymentBtnActionPerformed(evt);
            }
        });

        amountDueLabel.setText("Amount due");

        amountDueTextArea.setColumns(20);
        amountDueTextArea.setRows(5);
        jScrollPane1.setViewportView(amountDueTextArea);

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Parking Meter Application");

        minutesIncrementBtn.setText("+");
        minutesIncrementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutesIncrementBtnActionPerformed(evt);
            }
        });

        minutesDecrementBtn.setText("-");
        minutesDecrementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutesDecrementBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("How are you paying?");

        jLabel3.setText("R200.00");

        jLabel4.setText("R100.00");

        jLabel5.setText("R50.00");

        jLabel6.setText("R20.00");

        jLabel7.setText("R10.00");

        jLabel8.setText("R5.00");

        jLabel9.setText("R2.00");

        jLabel10.setText("R1.00");

        tenCentSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        twentyCentSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        fiftyCentSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        OneRandSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        twoRandSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        fiveRandSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        tenRandSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        twentyRandSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        payAmountBtn.setText("Pay");
        payAmountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payAmountBtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Change Hours");

        jLabel12.setText("Change Minutes");

        jLabel13.setText("R0.10");

        jLabel14.setText("R0.20");

        jLabel15.setText("R0.50");

        fiftyRandSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        oneHundredRandSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        twoHundredRandSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        jScrollPane2.setViewportView(outputTextArea);

        adminBtn.setText("Admin");
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        jLabel16.setText("Change Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amountDueLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(minutesIncrementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(hoursIncrementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hoursDecrementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(minutesDecrementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(exitDateLabel)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(exitDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(calculateExitDateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))
                                .addGap(176, 176, 176))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(79, 79, 79)
                                        .addComponent(prevDayEntryBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(nextDayEntryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(calculatePaymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entryDateLabel)
                                    .addComponent(entryDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(payAmountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(twoHundredRandSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                        .addComponent(twentyCentSpinner)
                                        .addComponent(tenCentSpinner)
                                        .addComponent(fiftyCentSpinner)
                                        .addComponent(OneRandSpinner)
                                        .addComponent(twoRandSpinner)
                                        .addComponent(fiveRandSpinner)
                                        .addComponent(tenRandSpinner)
                                        .addComponent(twentyRandSpinner)
                                        .addComponent(fiftyRandSpinner)
                                        .addComponent(oneHundredRandSpinner)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tenCentSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(twentyCentSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fiftyCentSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OneRandSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(twoRandSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fiveRandSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tenRandSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(twentyRandSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(exitDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calculateExitDateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fiftyRandSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oneHundredRandSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(twoHundredRandSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payAmountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calculatePaymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(224, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(entryDateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entryDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(prevDayEntryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nextDayEntryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(hoursIncrementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hoursDecrementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(minutesIncrementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(minutesDecrementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exitDateLabel)
                                .addGap(289, 289, 289)
                                .addComponent(amountDueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(59, 59, 59))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextDayEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextDayEntryBtnActionPerformed
        Object source = evt.getSource();
        
        if (source.equals(nextDayEntryBtn)){
            String currentDate =  entryDateTF.getText();
            
            DateSelector date = new DateSelector();
            String incrementDate  = date.incrementDate(new Date(currentDate));
            entryDateTF.setText(incrementDate.toString());
            
        }
    }//GEN-LAST:event_nextDayEntryBtnActionPerformed

    private void prevDayEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevDayEntryBtnActionPerformed
        Object source = evt.getSource();
        
        if(source.equals(prevDayEntryBtn)){
            String previousDate =  entryDateTF.getText();
            
            DateSelector date = new DateSelector();
            String decrementdate = date.decrementDate(new Date(previousDate));
            entryDateTF.setText(decrementdate.toString());
        }
    }//GEN-LAST:event_prevDayEntryBtnActionPerformed

    private void calculateExitDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateExitDateBtnActionPerformed
        Object source = evt.getSource();
        
        if(source.equals(calculateExitDateBtn)){
           DateSelector date = new DateSelector();
           String exitDateSelector = date.exitDateSelector();
           
           exitDateTF.setText(exitDateSelector);
           calculatePaymentBtn.setEnabled(true);
            
        }
    }//GEN-LAST:event_calculateExitDateBtnActionPerformed

    private void hoursIncrementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursIncrementBtnActionPerformed
        Object source = evt.getSource();
        
        if(source.equals(hoursIncrementBtn)){
            String currentTime = entryDateTF.getText();
            DateSelector date = new DateSelector();
            
            String hoursIncrement  = date.hoursIncrement(new Date(currentTime));
            entryDateTF.setText(hoursIncrement.toString());
             
        
        }
    }//GEN-LAST:event_hoursIncrementBtnActionPerformed

    private void hoursDecrementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursDecrementBtnActionPerformed
        Object source = evt.getSource();
        
        if(source.equals(hoursDecrementBtn)){
            String currentTime = entryDateTF.getText();
            
            DateSelector date = new DateSelector();
            
            String hoursDecrement  = date.hoursDecrement(new Date(currentTime));
            entryDateTF.setText(hoursDecrement.toString());
        
        }
    }//GEN-LAST:event_hoursDecrementBtnActionPerformed

    private void minutesIncrementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutesIncrementBtnActionPerformed
        Object source = evt.getSource();
        
        if(source.equals(minutesIncrementBtn)){
            String currentTime = entryDateTF.getText();
            DateSelector date = new DateSelector();
            
            String minutesIncrement  = date.minutesIncrement(new Date(currentTime));
            entryDateTF.setText(minutesIncrement.toString());
            
        
        }
    }//GEN-LAST:event_minutesIncrementBtnActionPerformed

    private void minutesDecrementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutesDecrementBtnActionPerformed
        Object source = evt.getSource();
        
        if(source.equals(minutesDecrementBtn)){
            String currentTime = entryDateTF.getText();
            DateSelector date = new DateSelector();
            
            String minutesDecrement  = date.minutesDecrement(new Date(currentTime));
            entryDateTF.setText(minutesDecrement.toString());
            
        
        }
    }//GEN-LAST:event_minutesDecrementBtnActionPerformed

    private void calculatePaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatePaymentBtnActionPerformed
        Object source = evt.getSource();
        
        if(source.equals(calculatePaymentBtn)){
            
            calculateParkingAmountModel.setEntryDate(entryDateTF.getText());
            calculateParkingAmountModel.setExitDate(exitDateTF.getText());
            
            TimeCalculator timeCalculator = new TimeCalculator();
            calculateParkingAmountModel = timeCalculator.calculateTime(calculateParkingAmountModel);
            
            FeeCalculator feeCalculator = new FeeCalculator();
            calculateParkingAmountModel = feeCalculator.timeCalcultor(calculateParkingAmountModel);
            
            amountDueTextArea.setText("R" + calculateParkingAmountModel.getTotalAmount().getFee());
            payAmountBtn.setEnabled(true);
            
       }
    }//GEN-LAST:event_calculatePaymentBtnActionPerformed

    private void payAmountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payAmountBtnActionPerformed
        Object source = evt.getSource();
        if(source.equals(payAmountBtn)){
            
            calculateParkingAmountModel.setTenCents((Integer) tenCentSpinner.getValue());
            calculateParkingAmountModel.setTwentyCents((Integer) twentyCentSpinner.getValue());
            calculateParkingAmountModel.setFiftyCents((Integer)fiftyCentSpinner.getValue());
            calculateParkingAmountModel.setOneRands((Integer)OneRandSpinner.getValue());
            calculateParkingAmountModel.setTwoRands((Integer)twoRandSpinner.getValue());
            calculateParkingAmountModel.setFiveRands((Integer)fiveRandSpinner.getValue());
            calculateParkingAmountModel.setTenRands((Integer)tenRandSpinner.getValue());
            calculateParkingAmountModel.setTwentyRands((Integer)twentyRandSpinner.getValue());
            calculateParkingAmountModel.setFiftyRands((Integer)fiftyRandSpinner.getValue());
            calculateParkingAmountModel.setOneHundredRands((Integer)oneHundredRandSpinner.getValue());
            calculateParkingAmountModel.setTwoHundredRands((Integer)twoHundredRandSpinner.getValue());
            
            MakePaymentCalculator makePaymentCalculator = new MakePaymentCalculator();
            calculateParkingAmountModel = makePaymentCalculator.paymentCalculator(calculateParkingAmountModel);
            calculateParkingAmountModel = makePaymentCalculator.calculateChange(calculateParkingAmountModel);
            
            CalculateDenominations calculateDenominations = new CalculateDenominations();
            CalculatePayModel calculatePayModel = calculateDenominations.denominations(calculateParkingAmountModel);
            
            outputTextArea.append("Time:" + "\n" );
            outputTextArea.append(Long.toString(calculateParkingAmountModel.getTotalHours()) + " Hours " +  Long.toString(calculateParkingAmountModel.getTotalMinutes()) + " Minutes" + "\n" + "\n");
            outputTextArea.append("You Entered:" + "\n");
            outputTextArea.append("R" + calculateParkingAmountModel.getPaidAmount() + "\n" + "\n" );
            outputTextArea.append("Your Change:" + "\n");
            outputTextArea.append("R" + calculateParkingAmountModel.getChangeAmount() + "\n" + "\n");
            outputTextArea.append("Denominations:"  + "\n");
            
            if(calculatePayModel.getTwoHundredRands() > 0 ) {
                outputTextArea.append("R200.00 x " + calculatePayModel.getTwoHundredRands() + "\n");
            }
            
            if(calculatePayModel.getOneHundredRands() > 0 ) {
                outputTextArea.append("R100.00 x " + calculatePayModel.getOneHundredRands() + "\n");
            }
            
            if(calculatePayModel.getFiftyRands() > 0 ) {
                outputTextArea.append("R50.00 x " + calculatePayModel.getFiftyRands() + "\n");
            }
            
            if(calculatePayModel.getTwentyRands() > 0 ) {
                outputTextArea.append("R20.00 x " + calculatePayModel.getTwentyRands() + "\n");
            }
            
            if(calculatePayModel.getTenRands() > 0 ) {
                outputTextArea.append("R10.00 x " + calculatePayModel.getTenRands() + "\n");
            }
            
            if(calculatePayModel.getFiveRands() > 0 ) {
                outputTextArea.append("R5.00 x " + calculatePayModel.getFiveRands() + "\n");
            }
            
            if(calculatePayModel.getTwoRands() > 0 ) {
                outputTextArea.append("R2.00 x " + calculatePayModel.getTwoRands() + "\n");
            }
            
            if(calculatePayModel.getOneRands() > 0 ) {
                outputTextArea.append("R1.00 x " + calculatePayModel.getOneRands() + "\n");
            }
            
            if(calculatePayModel.getFiftyCents() > 0 ) {
                outputTextArea.append("R0.50 x " + calculatePayModel.getFiftyCents() + "\n");
            }
            
            if(calculatePayModel.getTwentyCents() > 0 ) {
                outputTextArea.append("R0.20 x " + calculatePayModel.getTwentyCents() + "\n");
            }
            
            if(calculatePayModel.getTenCents() > 0 ) {
                outputTextArea.append("R0.10 x " + calculatePayModel.getTenCents() + "\n");
            }

             createTextFile.writeToTextFile(calculateParkingAmountModel, calculatePayModel);

        }
    }//GEN-LAST:event_payAmountBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        Object source = evt.getSource();
        
        if(source.equals(resetBtn)){
            createTextFile.clearTextFile();
        }
    }//GEN-LAST:event_resetBtnActionPerformed

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        Object source = evt.getSource();
        
        if(source.equals(adminBtn)){
            createTextFile.readFromTextFile();
        }
    }//GEN-LAST:event_adminBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParkingMeterMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParkingMeterMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParkingMeterMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParkingMeterMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParkingMeterMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner OneRandSpinner;
    private javax.swing.JButton adminBtn;
    private javax.swing.JLabel amountDueLabel;
    private javax.swing.JTextArea amountDueTextArea;
    private javax.swing.JButton calculateExitDateBtn;
    private javax.swing.JButton calculatePaymentBtn;
    private javax.swing.JLabel entryDateLabel;
    public static javax.swing.JTextField entryDateTF;
    private javax.swing.JLabel exitDateLabel;
    private javax.swing.JTextField exitDateTF;
    private javax.swing.JSpinner fiftyCentSpinner;
    private javax.swing.JSpinner fiftyRandSpinner;
    private javax.swing.JSpinner fiveRandSpinner;
    private javax.swing.JButton hoursDecrementBtn;
    private javax.swing.JButton hoursIncrementBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton minutesDecrementBtn;
    private javax.swing.JButton minutesIncrementBtn;
    private javax.swing.JButton nextDayEntryBtn;
    private javax.swing.JSpinner oneHundredRandSpinner;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JButton payAmountBtn;
    private javax.swing.JButton prevDayEntryBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JSpinner tenCentSpinner;
    private javax.swing.JSpinner tenRandSpinner;
    private javax.swing.JSpinner twentyCentSpinner;
    private javax.swing.JSpinner twentyRandSpinner;
    private javax.swing.JSpinner twoHundredRandSpinner;
    private javax.swing.JSpinner twoRandSpinner;
    // End of variables declaration//GEN-END:variables
}
